# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.5-browsers

    working_directory: ~/Top-Automation

    steps:
      - checkout
      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            behave -f allure_behave.formatter:AllureFormatter -o ./result ./features

      - run:
          name: generate allure
          command: sudo docker pull cashongo/allure-report-generator
          when: always

      - run:
          name: generate allure
          command: sudo docker run -v "./result:/allure-report" cashongo/allure-report-generator
          when: always

      - store_artifacts:
          path: artifacts
      - store_artifacts:
          path: result
      - store_artifacts:
          path: allure-report
destination: artifacts
destination: result
destination: allure-report